spring.application.name=LodwarTicketBackend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/lodwarticket
spring.datasource.username=lodwarticketadmin
spring.datasource.password=lodwarticketpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.property-naming-strategy=SNAKE_CASE